### PR TITLE
Export the sdm.devices.traits.ThermostatMode field in the metrics

### PR DESCRIPTION
**Pull request by cure**
Exported as a set of four gauges (nest_mode_heat, nest_mode_cool, nest_mode_heatcool, nest_mode_off).

### CODE REVIEW

**Review by klyubin — APPROVED** [review]
Thanks! This works perfectly on my thermostats.

This change breaks tests though.
```bash
$ go test ./...
?       pronestheus/cmd/pronestheus     [no test files]
?       pronestheus/test        [no test files]
ok      pronestheus/pkg 0.010s
--- FAIL: TestServerResponses (0.00s)
    --- FAIL: TestServerResponses/valid_response (0.00s)
        Error Trace:    1: 
        Error:          Not equal: &nest.Thermosta...Status: "OFF", Mode: "HEAT"}
            
FAIL
FAIL    pronestheus/pkg/collectors/nest 0.006s
ok      pronestheus/pkg/collectors/weather      0.008s
FAIL
```

The fix is:
```diff
diff --git a/pkg/collectors/nest/nest_test.go b/pkg/collectors/nest/nest_test.go
index ebad653..9d93580 100644
--- a/pkg/collectors/nest/nest_test.go
+++ b/pkg/collectors/nest/nest_test.go
@@ -28,6 +28,7 @@ func TestServerResponses(t *testing.T) {
                                SetpointTemp: float64(19.17838),
                                Humidity:     float64(57),
                                Status:       "OFF",
+                               Mode:         "HEAT",
                        },
                }, {
                        name:    "invalid auth token",
```

P. S. Consider adding a check for the new metrics in the `TestAllMetrics` test.

**Comment by cure** [comment]
Sorry about that! The tests are fixed, and I added asserts for the new gauges.

**Review by klyubin — APPROVED** [review]
Thank you very much.

Unfortunately, I'm not a maintainer of this project. So, my review doesn't let us merge this PR. :( I have a few PRs of my own too here in the same state...

**Comment by klyubin** [comment]
Because the owner of this repo hasn't responded to PRs since Dec 2022, I forked this repo as https://github.com/klyubin/pronestheus. I'll be happy to accept this PR there.

**Pull request closed without merging**
